backend:
  name: github
  repo: kewcoder/day2-static-blog-post

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { label: "Featured Image"
          ,name: "thumbnail"
          ,widget: "image"}
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      
